/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hyperloglogmethod;

import org.junit.Test;
import static org.junit.Assert.*;

import java.io.FileNotFoundException;

public class HashTest {
    // @Test public void appHasAGreeting() throws FileNotFoundException {
    //     assertNotNull("app should have a greeting", Hash.getGreeting());
    // }
}
